// Elementdata: [nummer, symbool, naam, massa, categorie, weetje, geheugensteun (optioneel)]
const CATEGORIEEN = {
  alkali:    { naam: "Alkalimetalen",        kleur: "#f2792b", uitleg: "Zachte, superreactieve metalen. In water gaan ze bruisen of zelfs knallen!" },
  aardalkali:{ naam: "Aardalkalimetalen",    kleur: "#4f86d6", uitleg: "Iets rustiger dan de alkalimetalen. Je vindt ze in botten, krijt en vuurwerk." },
  overgang:  { naam: "Overgangsmetalen",     kleur: "#33568f", uitleg: "Het grote blok in het midden: stevige, glimmende metalen zoals ijzer, koper en goud." },
  hoofdmetaal:{naam: "Hoofdgroepmetalen",    kleur: "#6b3fa0", uitleg: "Zachtere metalen rechts van het middenblok, zoals aluminium, tin en lood." },
  metalloide:{ naam: "Metalloïden",          kleur: "#6fae3a", uitleg: "Half metaal, half niet-metaal. Perfect voor computerchips!" },
  nietmetaal:{ naam: "Niet-metalen",         kleur: "#9ccc4e", uitleg: "De bouwstenen van het leven: waterstof, koolstof, stikstof, zuurstof…" },
  halogeen:  { naam: "Halogenen",            kleur: "#f4c21b", uitleg: "'Zoutvormers'. Ze maken graag verbindingen, zoals chloor in keukenzout." },
  edelgas:   { naam: "Edelgassen",           kleur: "#e0383e", uitleg: "Deftige gassen die met bijna niemand reageren. Ze gloeien mooi in lampen." },
  lanthaan:  { naam: "Lanthaniden",          kleur: "#c8264f", uitleg: "De 'zeldzame aarden'. Onmisbaar voor magneten, schermen en lasers." },
  actinide:  { naam: "Actiniden",            kleur: "#e86aa0", uitleg: "Zware, radioactieve elementen. De meeste zijn door mensen gemaakt." },
};

const ELEMENTEN_RUW = [
[1,"H","Waterstof","1,008","nietmetaal","Het lichtste element van allemaal. Het staat in groep 1, maar is géén metaal: het is een gas. De zon is een gigantische bal waterstof."],
[2,"He","Helium","4,003","edelgas","Lichter dan lucht: daarom zweven feestballonnen. Het werd eerst op de zon ontdekt (Helios = zon)."],
[3,"Li","Lithium","6,941","alkali","Zit in de accu van je telefoon. Zo licht dat het op olie blijft drijven."],
[4,"Be","Beryllium","9,012","aardalkali","Licht en keihard. De spiegels van de James Webb-ruimtetelescoop zijn van beryllium met een laagje goud."],
[5,"B","Boor","10,81","metalloide","Zit in borax, waarmee je slijm kunt maken, en in hittebestendig ovenglas."],
[6,"C","Koolstof","12,01","nietmetaal","Diamant én potloodstift zijn allebei puur koolstof! Alle levende wezens zijn erop gebouwd."],
[7,"N","Stikstof","14,01","nietmetaal","78% van de lucht die je inademt is stikstof. Vloeibaar is het −196 °C koud."],
[8,"O","Zuurstof","16,00","nietmetaal","Je ademt het elke seconde in. Het zit ook in water: H₂O = 2 waterstof + 1 zuurstof."],
[9,"F","Fluor","19,00","halogeen","Het meest reactieve element dat er is. Als fluoride in tandpasta beschermt het je tanden."],
[10,"Ne","Neon","20,18","edelgas","Geeft de rood-oranje gloed in neonreclames. Neos = nieuw."],
[11,"Na","Natrium","22,99","alkali","Samen met chloor vormt het keukenzout (NaCl). Een stukje natrium in water gaat sissen en knallen!","Na = NAtrium. Het Nederlandse woord is gewoon de Latijnse naam."],
[12,"Mg","Magnesium","24,31","aardalkali","Brandt met een verblindend wit licht, daarom zit het in vuurwerk en noodfakkels. Zit ook in groene bladeren."],
[13,"Al","Aluminium","26,98","hoofdmetaal","Frisdrankblikjes en aluminiumfolie. Het meest voorkomende metaal in de aardkorst."],
[14,"Si","Silicium","28,09","metalloide","Zand is grotendeels silicium + zuurstof. Computerchips zijn van silicium: vandaar 'Silicon Valley'."],
[15,"P","Fosfor","30,97","nietmetaal","Zit in het strijkvlak van een luciferdoosje, in je botten en in je DNA. Witte fosfor gloeit in het donker."],
[16,"S","Zwavel","32,06","nietmetaal","Gele stof uit vulkanen. Rotte eieren stinken door een zwavelverbinding.","S van Sulfur, het Latijnse woord voor zwavel."],
[17,"Cl","Chloor","35,45","halogeen","Die typische zwembadgeur? Dat is chloor dat bacteriën doodt. Ook de helft van keukenzout."],
[18,"Ar","Argon","39,95","edelgas","Bijna 1% van de lucht. Argos betekent 'lui': het reageert met niemand."],
[19,"K","Kalium","39,10","alkali","Bananen zitten er vol mee. Je spieren en zenuwen hebben het nodig.","K = Kalium. In het Nederlands makkelijk! (Engels zegt 'potassium'.)"],
[20,"Ca","Calcium","40,08","aardalkali","Maakt je botten en tanden sterk. Zit in melk, krijt en kalksteen."],
[21,"Sc","Scandium","44,96","overgang","Genoemd naar Scandinavië. Wordt gebruikt in lichte racefietsen."],
[22,"Ti","Titaan","47,87","overgang","Sterk en licht: vliegtuigen, brilmonturen en kunstheupen. Genoemd naar de reuzen (Titanen) uit Griekse mythen."],
[23,"V","Vanadium","50,94","overgang","Maakt gereedschap extra sterk: kijk maar eens op een steeksleutel ('chroom-vanadium')."],
[24,"Cr","Chroom","52,00","overgang","Maakt kranen en motoronderdelen glimmend. Roestvrij staal bevat chroom."],
[25,"Mn","Mangaan","54,94","overgang","Zit in gewone batterijen en maakt staal taaier."],
[26,"Fe","IJzer","55,85","overgang","De kern van de aarde is grotendeels ijzer. Ook je bloed is rood dankzij ijzer.","Fe = Ferrum, Latijn voor ijzer."],
[27,"Co","Kobalt","58,93","overgang","Geeft Delfts blauw zijn kleur! Zit ook in vitamine B12."],
[28,"Ni","Nikkel","58,69","overgang","Zit in de munten van 1 en 2 euro."],
[29,"Cu","Koper","63,55","overgang","Stroomdraden zijn van koper. Het Vrijheidsbeeld is van koper en daardoor groen geworden.","Cu = Cuprum, naar het eiland Cyprus waar de Romeinen koper haalden."],
[30,"Zn","Zink","65,38","overgang","Dakgoten zijn van zink. Een zinklaagje beschermt ijzer tegen roest."],
[31,"Ga","Gallium","69,72","hoofdmetaal","Smelt al bij 30 °C: het wordt vloeibaar in je hand!"],
[32,"Ge","Germanium","72,64","metalloide","Genoemd naar Duitsland (Germania). De allereerste transistors waren van germanium."],
[33,"As","Arseen","74,92","metalloide","Het beruchte gif uit detectiveverhalen van Agatha Christie."],
[34,"Se","Seleen","78,96","nietmetaal","Genoemd naar de maan (Selene). Je vindt het in paranoten."],
[35,"Br","Broom","79,90","halogeen","Een van maar twee elementen die vloeibaar zijn bij kamertemperatuur. Bromos = stank, en dat klopt!"],
[36,"Kr","Krypton","83,80","edelgas","Kryptoniet van Superman is verzonnen, krypton bestaat echt. Kryptos = verborgen."],
[37,"Rb","Rubidium","85,47","alkali","Kleurt een vlam dieprood (rubidus = rood). Gebruikt in atoomklokken."],
[38,"Sr","Strontium","87,62","aardalkali","Zorgt voor het knalrode vuurwerk op oudejaarsavond. Genoemd naar het Schotse dorp Strontian."],
[39,"Y","Yttrium","88,91","overgang","Genoemd naar het Zweedse dorpje Ytterby, net als ytterbium, terbium en erbium!"],
[40,"Zr","Zirkonium","91,22","overgang","Zirkonia is een nepdiamant die bijna net zo fonkelt als het echte werk."],
[41,"Nb","Niobium","92,91","overgang","Zit in de supermagneten van MRI-scanners. Genoemd naar Niobe uit de Griekse mythen."],
[42,"Mo","Molybdeen","95,94","overgang","Maakt staal keihard voor boren en fietsframes."],
[43,"Tc","Technetium","(98)","overgang","Het allereerste element dat door mensen is gemaakt (1937). Technetos = kunstmatig."],
[44,"Ru","Ruthenium","101,1","overgang","Genoemd naar Rusland (Ruthenia). Gebruikt in elektronica."],
[45,"Rh","Rhodium","102,9","overgang","Een van de duurste metalen ter wereld. Zit in de katalysator van auto's."],
[46,"Pd","Palladium","106,4","overgang","Ook in autokatalysatoren. Genoemd naar de planetoïde Pallas."],
[47,"Ag","Zilver","107,9","overgang","Geleidt stroom beter dan elk ander metaal. Argentinië betekent 'zilverland'!","Ag = Argentum, Latijn voor zilver. Denk aan ARGentinië."],
[48,"Cd","Cadmium","112,4","overgang","Giftig metaal dat vroeger in oplaadbare batterijen en gele verf zat."],
[49,"In","Indium","114,8","hoofdmetaal","Zit in het aanraakscherm van je telefoon. Genoemd naar de kleur indigo."],
[50,"Sn","Tin","118,7","hoofdmetaal","Tinnen soldaatjes en soldeertin. Een conservenblik is staal met een laagje tin.","Sn = Stannum, Latijn voor tin."],
[51,"Sb","Antimoon","121,8","metalloide","Oude Egyptenaren gebruikten het als zwarte oogmake-up.","Sb = Stibium, de Latijnse naam."],
[52,"Te","Telluur","127,6","metalloide","Genoemd naar de aarde (Tellus). Zit in sommige zonnepanelen."],
[53,"I","Jood","126,9","halogeen","Er zit jodium in bakkerszout, zodat je schildklier goed werkt.","I = Iodium. In het Engels heet jood 'iodine'."],
[54,"Xe","Xenon","131,3","edelgas","Voor felle koplampen en de ionenmotoren van ruimtesondes. Xenos = vreemdeling."],
[55,"Cs","Cesium","132,9","alkali","Cesium-atoomklokken bepalen hoe lang een seconde precies duurt."],
[56,"Ba","Barium","137,3","aardalkali","Geeft groen vuurwerk. Bij een röntgenfoto van je darmen drink je soms bariumpap."],
[57,"La","Lanthaan","138,9","lanthaan","Zit in cameralenzen. Lanthanein = verborgen zijn."],
[58,"Ce","Cerium","140,1","lanthaan","Zit in het vuursteentje van een aansteker. Genoemd naar dwergplaneet Ceres."],
[59,"Pr","Praseodymium","140,9","lanthaan","Kleurt glas geelgroen. De naam betekent 'groene tweeling'."],
[60,"Nd","Neodymium","144,2","lanthaan","De sterkste magneten ter wereld, bijvoorbeeld in oortjes en elektromotoren."],
[61,"Pm","Promethium","(145)","lanthaan","Radioactief en zeldzaam. Genoemd naar Prometheus, die het vuur stal van de goden."],
[62,"Sm","Samarium","150,4","lanthaan","Maakt magneten die tegen hitte kunnen."],
[63,"Eu","Europium","152,0","lanthaan","Laat eurobiljetten oplichten onder uv-licht, tegen vervalsing. Genoemd naar Europa!"],
[64,"Gd","Gadolinium","157,3","lanthaan","Wordt gebruikt als contrastmiddel bij MRI-scans."],
[65,"Tb","Terbium","158,9","lanthaan","Geeft groen licht in schermen en lampen. Weer een Ytterby-element!"],
[66,"Dy","Dysprosium","162,5","lanthaan","Dysprositos = moeilijk te krijgen. Nodig voor magneten in elektrische auto's."],
[67,"Ho","Holmium","164,9","lanthaan","Genoemd naar Stockholm (Holmia)."],
[68,"Er","Erbium","167,3","lanthaan","Versterkt het licht in glasvezelkabels: zonder erbium geen snel internet!"],
[69,"Tm","Thulium","168,9","lanthaan","Een van de zeldzaamste lanthaniden. Thule is een oude naam voor het verre noorden."],
[70,"Yb","Ytterbium","173,0","lanthaan","Het vierde element genoemd naar Ytterby. Gebruikt in superprecieze atoomklokken."],
[71,"Lu","Lutetium","175,0","lanthaan","Lutetia is de oude Romeinse naam voor Parijs."],
[72,"Hf","Hafnium","178,5","overgang","Hafnia = Kopenhagen. Wordt gebruikt in kerncentrales om de reactie af te remmen."],
[73,"Ta","Tantaal","180,9","overgang","Zit in kleine onderdelen van telefoons. Genoemd naar Tantalus uit de Griekse mythen."],
[74,"W","Wolfraam","183,8","overgang","Het hoogste smeltpunt van alle metalen: 3422 °C! Gloeidraad in ouderwetse gloeilampen.","W = Wolfraam. Makkelijk in het Nederlands (Engels: tungsten)."],
[75,"Re","Renium","186,2","overgang","Genoemd naar de Rijn (Rhenus)! Zit in straalmotoren van vliegtuigen."],
[76,"Os","Osmium","190,2","overgang","Het zwaarste element per liter: een blokje zo groot als een melkpak weegt 22 kilo."],
[77,"Ir","Iridium","192,2","overgang","Een laagje iridium in de bodem bewijst dat een meteoriet de dinosaurussen uitroeide."],
[78,"Pt","Platina","195,1","overgang","Kostbaar voor sieraden. Platina is Spaans voor 'zilvertje'."],
[79,"Au","Goud","197,0","overgang","Goud roest nooit. Al het goud ooit gedolven past in zo'n vier olympische zwembaden.","Au = Aurum, Latijn voor goud."],
[80,"Hg","Kwik","200,6","overgang","Het enige metaal dat vloeibaar is bij kamertemperatuur. Vroeger in thermometers.","Hg = Hydrargyrum: 'vloeibaar zilver'. Ezelsbruggetje: Kwik is Heel Giftig."],
[81,"Tl","Thallium","204,4","hoofdmetaal","Heel giftig. Kleurt een vlam groen (thallos = groene twijg)."],
[82,"Pb","Lood","207,2","hoofdmetaal","Vroeger waren waterleidingen van lood.","Pb = Plumbum. Daarom heet een loodgieter in het Engels 'plumber'!"],
[83,"Bi","Bismut","209,0","hoofdmetaal","Vormt prachtige regenboogkleurige trapjeskristallen."],
[84,"Po","Polonium","(209)","metalloide","Ontdekt door Marie Curie en genoemd naar haar vaderland Polen."],
[85,"At","Astaat","(210)","halogeen","Het zeldzaamste natuurlijke element: op de hele aarde is er op elk moment maar een piepklein beetje van. Astatos = onstabiel."],
[86,"Rn","Radon","(222)","edelgas","Radioactief gas dat uit de bodem komt en in kelders kan ophopen."],
[87,"Fr","Francium","(223)","alkali","Genoemd naar Frankrijk. Zo zeldzaam dat niemand ooit een zichtbaar stukje heeft gezien."],
[88,"Ra","Radium","(226)","aardalkali","Gloeit in het donker. Vroeger op wijzerplaten van klokken, tot men ontdekte hoe gevaarlijk het is."],
[89,"Ac","Actinium","(227)","actinide","Geeft een spookachtige blauwe gloed in het donker. Aktis = straal."],
[90,"Th","Thorium","232,0","actinide","Genoemd naar Thor, de Noorse god van de donder!"],
[91,"Pa","Protactinium","(231)","actinide","Betekent 'vóór actinium', omdat het in actinium verandert."],
[92,"U","Uraan","238,0","actinide","Brandstof voor kerncentrales, zoals die in Borssele. Genoemd naar de planeet Uranus."],
[93,"Np","Neptunium","(237)","actinide","Genoemd naar Neptunus, de planeet ná Uranus."],
[94,"Pu","Plutonium","(244)","actinide","Genoemd naar Pluto. Levert stroom voor ruimtesondes zoals de Voyagers."],
[95,"Am","Americium","(243)","actinide","Zit in een piepklein beetje in veel rookmelders! Genoemd naar Amerika."],
[96,"Cm","Curium","(247)","actinide","Genoemd naar Marie en Pierre Curie."],
[97,"Bk","Berkelium","(247)","actinide","Gemaakt in Berkeley, Californië."],
[98,"Cf","Californium","(251)","actinide","Genoemd naar Californië. Gebruikt om olie en goud op te sporen."],
[99,"Es","Einsteinium","(252)","actinide","Genoemd naar Albert Einstein. Ontdekt in het puin van de eerste waterstofbom."],
[100,"Fm","Fermium","(257)","actinide","Genoemd naar natuurkundige Enrico Fermi."],
[101,"Md","Mendelevium","(258)","actinide","Genoemd naar Dmitri Mendelejev: de bedenker van het periodiek systeem!"],
[102,"No","Nobelium","(259)","actinide","Genoemd naar Alfred Nobel, van de Nobelprijs."],
[103,"Lr","Lawrencium","(262)","actinide","Genoemd naar Ernest Lawrence, uitvinder van de deeltjesversneller (cyclotron)."],
[104,"Rf","Rutherfordium","(267)","overgang","Genoemd naar Ernest Rutherford, die de atoomkern ontdekte."],
[105,"Db","Dubnium","(268)","overgang","Genoemd naar Dubna, een Russische onderzoeksstad."],
[106,"Sg","Seaborgium","(269)","overgang","Genoemd naar Glenn Seaborg, terwijl hij nog leefde. Dat was nog nooit gebeurd!"],
[107,"Bh","Bohrium","(270)","overgang","Genoemd naar Niels Bohr, bekend van het atoommodel."],
[108,"Hs","Hassium","(269)","overgang","Genoemd naar de Duitse deelstaat Hessen (Hassia)."],
[109,"Mt","Meitnerium","(278)","overgang","Genoemd naar Lise Meitner, die uitlegde hoe kernsplijting werkt."],
[110,"Ds","Darmstadtium","(281)","overgang","Genoemd naar de Duitse stad Darmstadt, waar het gemaakt werd."],
[111,"Rg","Roentgenium","(281)","overgang","Genoemd naar Wilhelm Röntgen, van de röntgenfoto."],
[112,"Cn","Copernicium","(285)","overgang","Genoemd naar Copernicus, die zei dat de aarde om de zon draait."],
[113,"Nh","Nihonium","(286)","hoofdmetaal","Nihon = Japan. Het eerste element dat in Azië werd ontdekt."],
[114,"Fl","Flerovium","(289)","hoofdmetaal","Genoemd naar het Flerov-laboratorium in Rusland."],
[115,"Mc","Moscovium","(288)","hoofdmetaal","Genoemd naar de regio Moskou. Bestaat maar een fractie van een seconde."],
[116,"Lv","Livermorium","(293)","hoofdmetaal","Genoemd naar het Lawrence Livermore-lab in Californië."],
[117,"Ts","Tennessine","(294)","halogeen","Genoemd naar de Amerikaanse staat Tennessee."],
[118,"Og","Oganesson","(294)","edelgas","Het zwaarste element dat ooit is gemaakt! Genoemd naar de Russische onderzoeker Joeri Oganesjan."],
];

// Plaats in het rooster [rij, kolom]; rij 9 = lanthaniden, rij 10 = actiniden
function positie(n) {
  if (n === 1) return [1, 1];
  if (n === 2) return [1, 18];
  if (n <= 4) return [2, n - 2];
  if (n <= 10) return [2, n + 8];
  if (n <= 12) return [3, n - 10];
  if (n <= 18) return [3, n];
  if (n <= 36) return [4, n - 18];
  if (n <= 54) return [5, n - 36];
  if (n <= 56) return [6, n - 54];
  if (n <= 71) return [9, n - 54];
  if (n <= 86) return [6, n - 68];
  if (n <= 88) return [7, n - 86];
  if (n <= 103) return [10, n - 86];
  return [7, n - 100];
}

const ELEMENTEN = ELEMENTEN_RUW.map(([nr, sym, naam, massa, cat, weetje, tip]) => {
  const [rij, kol] = positie(nr);
  return { nr, sym, naam, massa, cat, weetje, tip, rij, kol };
});

// Bestaande Nederlandse ezelsbruggetjes (niet zelf verzonnen), met bron.
// Vetgedrukte letters = de symbolen.
const EZELSBRUGGETJES = [
  { titel: "De eerste 20 elementen", elementen: "H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca",
    zin: "<b>H</b>a <b>He</b> <b>Li</b>eve <b>Be</b>ste <b>B</b>olle <b>C</b>or, <b>N</b>oem <b>O</b>nze <b>F</b>ee <b>Ne</b>eltje <b>Na</b>atje, <b>M</b>a<b>g</b> <b>Al</b>les <b>Si</b>en <b>P</b>iet, <b>S</b>not <b>Cl</b>ungelt <b>Ar</b>moedig, <b>K</b>ouwe <b>Ca</b>ke",
    bron: "ezelsbrug.nl", url: "https://www.ezelsbrug.nl/scheikunde/hhelibebcnofnenamgalsipsclarkca/" },
  { titel: "De eerste 18 elementen (kort)", elementen: "H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar",
    zin: "<b>H</b>a, <b>he</b>! <b>Li</b>eve <b>Beb</b>, <b>cnof</b> <b>ne</b>e! <b>Namgal</b> <b>sips</b> <b>clar</b>.",
    noot: "Lees de klanken als symbolen: Na-Mg-Al, Si-P-S, Cl-Ar.",
    bron: "madeeurope.wordpress.com", url: "https://madeeurope.wordpress.com/2013/12/29/ha-he-lieve-beb-cnof-nee/" },
  { titel: "Groep 1: waterstof en de alkalimetalen", elementen: "H Li Na K Rb Cs Fr",
    zin: "<b>H</b>ilde <b>li</b>gt <b>na</b>ast <b>K</b>arel, <b>R</b>o<b>b</b>, <b>C</b>ee<b>s</b> en <b>Fr</b>ank",
    noot: "Let op: waterstof staat bovenaan groep 1, maar is géén metaal. Het is een niet-metaal (een gas). De alkalimetalen zijn Li t/m Fr.",
    bron: "ezelsbrug.nl", url: "https://www.ezelsbrug.nl/scheikunde/" },
  { titel: "Edelgassen (groep 18)", elementen: "Ne He Ar Kr Rn Xe",
    zin: "<b>NE</b>e <b>HE</b>, <b>AR</b>mani en <b>KR</b>is zijn ook niet in de <b>RA</b>bobank of de <b>XE</b>nos",
    noot: "Let op: RA staat voor radon, maar het symbool van radon is <b>Rn</b>. De volgorde in het rooster is He, Ne, Ar, Kr, Xe, Rn.",
    bron: "ezelsbruggetje.nl", url: "https://ezelsbruggetje.nl/ezelsbruggetjes/edelgassen/" },
  { titel: "Halogenen (groep 17)", elementen: "Br F I Cl",
    zin: "<b>BR</b>om<b>FI</b>ets<b>CL</b>ub",
    noot: "Broom, fluor, jood en chloor. (Astaat en tennessine zijn ook halogenen, maar zeldzaam.)",
    bron: "ezelsbruggetje.nl", url: "https://ezelsbruggetje.nl/vakken/scheikunde/" },
  { titel: "Elementen die in paren voorkomen (H₂, O₂, …)", elementen: "Br I N Cl H O F",
    zin: "<b>BrINClHOF</b>",
    noot: "Deze zeven komen als los element altijd met twee atomen tegelijk voor: Br₂, I₂, N₂, Cl₂, H₂, O₂ en F₂.",
    bron: "ezelsbruggetje.nl", url: "https://ezelsbruggetje.nl/vakken/scheikunde/" },
  { titel: "Dezelfde zeven, als zin", elementen: "F Cl Br I O H N",
    zin: "<b>F</b>ien <b>Cl</b>iederde <b>Br</b>uine <b>I</b>nkt <b>O</b>p <b>H</b>aar <b>N</b>eus",
    bron: "ezelsbruggetje.nl", url: "https://ezelsbruggetje.nl/vakken/scheikunde/" },
  { titel: "Kwik", elementen: "Hg",
    zin: "Kwik is <b>H</b>eel <b>G</b>iftig",
    bron: "ezelsbrug.nl", url: "https://www.ezelsbrug.nl/scheikunde/" },
];
